experiment with tests on gha

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,5 +1,9 @@
 name: Build 
 
+permissions:
+    contents: read
+    checks: write
+
 on:
   push:
     branches: [ "main" ]
@@ -13,13 +17,35 @@ jobs:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: make deps 
-    - name: make
+    - name: Make the regular binary 
       run: make
-    - name: release
+      
+    - name: Tests
+      run: make test-junit-gha
+
+    - name: debug
+      if: success() || failure()
+      run: ls -la .
+      
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: './result-junit.xml'
+      
+    - name: Release regular binary 
       uses: actions/upload-artifact@v4
       with:
         name: Mac release 
         path: ./finropedemo
+        if-no-files-found: error 
+        retention-days: 1 
+        overwrite: true
+    - name: Release binary with tests 
+      uses: actions/upload-artifact@v4
+      with:
+        name: Mac test release 
+        path: ./finropedemotests
         if-no-files-found: error 
         retention-days: 1 
         overwrite: true
